"use client";
import { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import "./styles.css";
const metadata: Metadata = {
  title: {
    absolute: "This is register",
    default: "This is default title",
    template: "%s | Demo Next",
  },
  description: "Generated by Next.js",
};

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgot-password" },
  { name: "Blog", href: "/blog" },
  { name: "Products", href: "/products" },
];

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <>
      <div className="flex gap-2">
        {navLinks?.map((item) => {
          const isActive = pathname.startsWith(item.href);
          console.log("dfsadf", pathname, isActive);
          return (
            <Link
              key={item?.href}
              href={item?.href}
              className={`mr-2
                    ${
                      isActive
                        ? "font-[900] text-[#292561]"
                        : "text-[blue] font-light"
                    }`}
            >
              {item?.name}
            </Link>
          );
        })}
      </div>
      {children}
    </>
  );
}
